project_id = "iwivgqsihxicyptaoewm"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.parse-rate-confirmation]
verify_jwt = false

[functions.parse-landstar-statement]
verify_jwt = false

[functions.check-pm-schedules]
verify_jwt = true


[functions.storage-proxy]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.public-load-tracker]
verify_jwt = false

[functions.delete-own-account]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.email-load-status]
verify_jwt = false

[functions.contact-form]
verify_jwt = false


[functions.accept-invitation]
verify_jwt = true
