project_id = "iwivgqsihxicyptaoewm"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.parse-rate-confirmation]
verify_jwt = false

[functions.parse-landstar-statement]
verify_jwt = false

[functions.check-pm-schedules]
verify_jwt = true

[functions.landstar-fuel-stops]
verify_jwt = false

[functions.manage-credentials]
verify_jwt = false

[functions.storage-proxy]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.public-load-tracker]
verify_jwt = false

